# Generated by Django 3.1.2 on 2020-11-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Email',
            new_name='email',
        ),
    ]
