# Generated by Django 3.1.2 on 2020-11-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_patient_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='password1',
            new_name='password',
        ),
    ]
