# Generated by Django 3.1.2 on 2020-11-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201115_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
