# Generated by Django 3.1.2 on 2020-11-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201115_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default=' ', editable='false', max_length=50),
        ),
    ]
